### ISSUE TITLE
Output hangs when testing self-referencing data.

### ISSUE THREAD

**Issue by sushi-buffer** [fukamachi/rove#11]
A test like this causes the output to hang:

```lisp
...
(let ((foo '(1 2 3)))
  (setf (cdddr foo) foo)
  (ok (equal foo #1=(1 2 3 . #1#))))
...
```

**Comment by ghost** [comment]
Ha! I was simply being an idiot. `(setf *print-circle* t)` works wonders and of course it's `'#1=(1 2 3 #1#)`. Sorry for pestering you with issues, 8arrow! 😅
