### ISSUE TITLE
LET variables leak onto next test

### ISSUE THREAD

**Issue by sushi-buffer** [fukamachi/rove#14]
Here's a case where let variable that's inside another scope somehow bleeds into another test causing surprising results:

```lisp
(deftest cl-sequence-types
  (testing
   "Generic functions for SEQUENCE subtypes:"
      (testing
       "A 'SETF' -function:"
	(testing (format
		  nil
		  "Allows setting sequence contents with~@
                   a combination of 'SETF' and 'ELT':")
	  (let ((vec-seq  (vector 1 2 3))
		(list-seq '(1 2 3)))
	    (ok (= (setf (elt vec-seq 0) 10)  10))
	    (ok (equalp vec-seq '#(10 2 3)))
	    (ok (= (setf (elt list-seq 0) 10) 10))
	    (ok (equalp list-seq '(10 2 3)))))
	(skip "NOTE: More about 'SETF' on variable handling!"))
      (testing
	  (format
	   nil
	   "'SUBSTITUTE' and it's derivatives.~@
            Has 'KTTN' and ':start', ':end' and ':from-end'~@
            as kargs and 'NSUBSTITUTE' -versions:~@
            ~@T - 'SUBSTITUTE' ~@
            ~@T - 'SUBSTITUTE-IF' ~@
            ~@T - 'SUBSTITUTE-IF-NOT' ")
	(let ((vec-seq  (vector 1 2 3))
	      (list-seq '(1 2 3)))
	  (ok (equalp
	       (substitute 10 2 vec-seq)
	       '#(1 10 3)))
	  (ok (equalp
	       (substitute 10 3 list-seq)
	       '(1 2 10)))))))

```

This results the `list-seq` inside the latter test to start off as what was set on the previous `'(10 2 3)` test, instead of the declared `'(1 2 3)` causing a surprising fail:

```
Expect (EQUALP (SUBSTITUTE 10 3 LIST-SEQ) '(1 2 10)) to be true.
     (EQUALP
      #1=(SUBSTITUTE 10 3
                     MASTER-CLASS/TEST/BASICS/COLLECTIONS/SEQUENCE-TYPES::LIST-SEQ)
      '(1 2 10))
         LIST-SEQ = (10 2 3)
         #1# = (10 2 10)
```

**Comment by ghost** [comment]
Curiously I've noticed this only happens if variables are lists!

**Comment by ghost** [comment]
Any word about this?

**Comment by fukamachi** [comment]
Can't reproduce it with your code.
What implementation and version are you using?

**Comment by ghost** [comment]
Hi! Thanks for the reply! :)

lisp implementation & version: SBCL 1.4.12
rove version: rove-20181018-git / quicklisp 2018-10-18

**Comment by fukamachi** [comment]
Thanks, but still can't reproduce it.

I tried the following steps:

1. ros -L sbcl/1.4.12 run
2. `(ql:quickload :rove)`
3. `(use-package :rove)`
4. Paste your code
5. `(rove:run-test 'cl-sequence-types)`
6. All passed.

**Comment by ghost** [comment]
Hmm.. interesting! When I do the same it does pass! When i attempt to run it from the package via (rove:run :some/path/to/test :style :spec) it fails with the previously provided information.

For example if I define a package like this:

```lisp
(in-package #:cl-user)
(defpackage #:master-class/test/testing
  (:use #:cl #:rove))
(in-package #:master-class/test/testing)

(deftest cl-sequence-types
  (testing
   "Generic functions for SEQUENCE subtypes:"
      (testing
       "A 'SETF' -function:"
	(testing (format
		  nil
		  "Allows setting sequence contents with~@
                   a combination of 'SETF' and 'ELT':")
	  (let ((vec-seq  (vector 1 2 3))
		(list-seq '(1 2 3)))
	    (ok (= (setf (elt vec-seq 0) 10)  10))
	    (ok (equalp vec-seq '#(10 2 3)))
	    (ok (= (setf (elt list-seq 0) 10) 10))
	    (ok (equalp list-seq '(10 2 3)))))
	(skip "NOTE: More about 'SETF' on variable handling!"))
      (testing
	  (format
	   nil
	   "'SUBSTITUTE' and it's derivatives.~@
            Has 'KTTN' and ':start', ':end' and ':from-end'~@
            as kargs and 'NSUBSTITUTE' -versions:~@
            ~@T - 'SUBSTITUTE' ~@
            ~@T - 'SUBSTITUTE-IF' ~@
            ~@T - 'SUBSTITUTE-IF-NOT' ")
	(let ((vec-seq  (vector 1 2 3))
	      (list-seq '(1 2 3)))
	  (ok (equalp
	       (substitute 10 2 vec-seq)
	       '#(1 10 3)))
	  (ok (equalp
	       (substitute 10 3 list-seq)
	       '(1 2 10)))))))
```

and then on REPL run:

(rove:run :master-class/test/testing :style :spec)

I get the same issue. This also happens when I attempt to run my test suites with asdf.

**Comment by fukamachi** [comment]
Perhaps, SBCL optimizes it somehow by taking a constant list `'(1 2 3)` as the same object.
I'll look into this when I have time.
Use `(list 1 2 3)` instead for now, since applying a destructive function to a quoted list is not a good manner anyway.

**Comment by ghost** [comment]
I shall :) thanks for taking a look and let me know if you find something. It's interesting to get to know the internals! :)

**Comment by ghost** [comment]
Noticed the same thing happens if you declare a string as a let too. As in (let ((foo "testing"))). If I modify this and declare another let inside another test, the previous modification affects this string too!

**Comment by ghost** [comment]
Hmm.. I'll add info that replacing `(let ((foo "testing")))` with `(let ((foo (string "testing"))))` doesn't stop the error from happening, unlike with lists and vectors. Why is this?

**Comment by fukamachi** [comment]
Because ‘string’ returns the argument with no modifications/allocations if
it’s a string.
http://www.lispworks.com/documentation/lw50/CLHS/Body/f_string.htm


2019年2月11日(月) 14:46 4lph4-Ph4un <notifications@github.com>:

**Comment by ghost** [comment]
Ah I see. So with lists and vectors the function results in binding that SBCL would not optimize erroneusly, but with strings there are no difference unless we force the function to allocate somehow? Would using symbols as parameters to `(string)` perhaps provide a workaround that would make tests work in SBCL?

**Comment by fukamachi** [comment]
Or copy-seq, I suppose.

**Comment by ghost** [comment]
Okay! I'll give it a try! :) Is there anything new and coming for Rove in the future?

**Comment by fukamachi** [comment]
I don't have a clear picture of this project, but there're some features I want to add now (ex. more reporters, code coverage report and parallel execution of test suites).
