### ISSUE TITLE
Running tests from the REPL

### ISSUE THREAD

**Issue by gosukiwi** [fukamachi/rove#16]
Hello there, first of all, thanks for sharing this library, I've used prove before and it's great. Given this will (ideally) replace it, I want to use this one for my new project.

The thing is, I'm using Windows to develop right now, and `ros exec rove` doesn't work. Is there a way to run the tests using the REPL instead? Kind of like `prove:run`.

I am new to Common Lisp in general so forgive me if I am missing something obvious.

Thanks!

**Comment by fukamachi** [comment]
Thanks for using Prove and also getting interested in Rove.
You can use `rove:run` as the same as `prove:run`.

**Comment by fukamachi** [comment]
I found the difference. `rove:run` cannot use for files, since Rove accepts ASDF systems as test suites.

**Comment by gosukiwi** [comment]
Oh! I see. I'm dumb. Sorry about that :) Thanks for taking the time to reply!
