### ISSUE TITLE
ASD format and ABCL portability: regressions since 2 commits after b204929

### ISSUE THREAD

**Issue by jonatack** [fukamachi/rove#17]
Hi @fukamachi, thank you for creating ROVE. 

I seem to have come across 2 regressions since the latest 2 commits to master:

- In the .ASD file, non-string DEFSYSTEM :DEPENDS-ON parameters cause ROVE to raise type errors: `"The value #:PACKAGE is not of type sequence")`. Changing all of them to strings is a workaround.

- Rove has been working well for me with SBCL, CCL, CLISP, ABCL, and ECL, but now in Armed Bear Common Lisp, the tests compile but they no longer run, i.e. `✓ 0 tests completed`.

Reverting the 2 latest commits in master with

```bash
cd ~/quicklisp/local-projects/rove && git reset --hard b204929
```
solves both regressions.

Thanks again for this useful testing library :+1:

**Comment by fukamachi** [comment]
Thank you for reporting this.
I've never checked Rove seriously with all implementation other than SBCL, however, it's great to hear its portability is not so bad.

I guess that it because Rove expects `asdf:component-sideway-dependencies` returns a list of strings, though it may be a list of symbols.
https://github.com/fukamachi/rove/blob/master/core/suite/file.lisp#L50-L55

Could you tell me the version of ABCL and ASDF on your test environment?
I'd like to test it on my local machine, and make sure it will be resolved by the change.

**Comment by fukamachi** [comment]
For the record, I just installed these versions of ABCL & ASDF on my machine:

```
CL-USER(1): (lisp-implementation-version)
"1.5.0"
"Java_HotSpot(TM)_64-Bit_Server_VM-Oracle_Corporation-11+28"
"x86_64-Mac_OS_X-10.13.6"
CL-USER(2): (asdf:asdf-version)
"3.2.1"
CL-USER(3):
```

**Comment by jonatack** [comment]
Thank you for your quick reply. I should have added more information to reproduce.

In addition to SBCL, which is the primary target, Rove has been working well with:
- ClozureCL 1.11.5
- CLISP 2.49.92
- ABCL 1.5.0 and 1.6.0dev master
-  ECL 16.1.3

all on Linux x86/64.

The regressions were found while running the tests in https://github.com/jonatack/cl-kraken (which also uses Quri and Dexador, thank you for those).

I run the tests with `(asdf:test-system :cl-kraken)`.

**Comment by jonatack** [comment]
Thank you for your quick reply. I should have added more information to reproduce.

```lisp
CL-USER(1): (lisp-implementation-version)
"1.6.0-dev"
"OpenJDK_64-Bit_Server_VM-Oracle_Corporation-1.8.0_171-8u171-b11-2-b11"
"amd64-Linux-4.19.0-2-amd64"
CL-USER(2): (asdf:asdf-version)
"3.3.2.13"
```

In addition to SBCL, which is the primary target, Rove has been working well with:
- ClozureCL 1.11.5
- CLISP 2.49.92
- ABCL 1.5.0 and 1.6.0-dev
-  ECL 16.1.3

all on Linux x86/64.

The regressions were found while running the tests in https://github.com/jonatack/cl-kraken (which also uses Quri and Dexador, thank you for those).

I run the tests with `(asdf:test-system :cl-kraken)` or `(rove:run :cl-kraken/tests)`.

**Comment by fukamachi** [comment]
The issue may possibly be fixed at https://github.com/fukamachi/rove/commit/e4f8d8eed23ec4aad3796b5fb95e08e968d76195.
Could you recheck with the latest Rove?

**Comment by jonatack** [comment]
Both issues are now resolved on all the CL implementation versions mentioned above. Thanks!

```lisp
Armed Bear Common Lisp 1.6.0-dev
Java 1.8.0_171 Oracle Corporation
OpenJDK 64-Bit Server VM
Low-level initialization completed in 0.305 seconds.
Startup completed in 1.437 seconds.

CL-USER(1): (rove:run :cl-kraken/tests :style :dot)


;; testing 'cl-kraken/tests/time'
.....

;; testing 'cl-kraken/tests/cryptography'
....

;; testing 'cl-kraken/tests/http'
.

;; testing 'cl-kraken/tests/main'
....................................................................................
✓ 4 tests completed

Summary:
  All 4 tests passed.
T
(#<ROVE/CORE/RESULT:PASSED-TEST {510697AA}> #<ROVE/CORE/RESULT:PASSED-TEST {6AD932AD}>
 #<ROVE/CORE/RESULT:PASSED-TEST {7B6328D6}> #<ROVE/CORE/RESULT:PASSED-TEST {451F4D74}>)
NIL
CL-USER(2): 
```
