### ISSUE TITLE
Run tests on eval?

### ISSUE THREAD

**Issue by mdbergmann** [fukamachi/rove#23]
Hi.

Is there a way to run the defined tests on C-c C-k?

AFAIR in Prove this worked, in FiveAM I've adding a (run! 'test) in to the test lisp file.

**Comment by fukamachi** [comment]
Put `(run-suite *package*)` at the end of test files.

```common-lisp
(defpackage #:rove-example
  (:use #:cl
        #:rove))
(in-package #:rove-example)

(deftest example
  (ok (= 1 1)))

(run-suite *package*)
```
