### ISSUE TITLE
installation instructions should include instructions for getting rove binary

### ISSUE THREAD

**Issue by tychoish** [fukamachi/rove#32]
I did `ros build roswell/rove.ros && mv rove /usr/local/bin/` which might not be to everyone's liking but some indication of how to do this would be nice!

**Comment by AlbertoEAF** [comment]
Yeah, I really want to use rove to test stuff but I simply cannot understand where the "rove" command comes from in the tutorial. Already lost 2 nights trying to figure out how. (Disclaimer: I'm just starting and still am very noob at CL.). Btw, @tychoish's suggestion worked, now it's my setup of system/packages that still gives me errors, but I can launch rove like that (and it works in the REPL).

**Comment by vindarel** [comment]
I installed it with `ros install rove`. To install Roswell: https://github.com/roswell/roswell/wiki/Installation (there are Debian packages)
