### ISSUE TITLE
Question about plans!

### ISSUE THREAD

**Issue by sushi-buffer** [fukamachi/rove#4]
What's the initial timetable for Beta? :)

**Comment by AeroNotix** [comment]
I've been using rove. Far superior than anything I've used before.

**Comment by ghost** [comment]
Hmmm! think I'm going to give it a try then! :) I'm fairly n00b in CLisp currently, but I think checking out amazing technologies such as this is really benefical for your learning. Can you recommend a good general sources for learning CLisp by the way? I don't know anyone in real life that is even remotely interested in it (unfortunately!), and besides official documentation some good sources for learning are hard to come by! :)

**Comment by AeroNotix** [comment]
#lisp on freenode
[the Practical Common Lisp book](http://www.gigamonkeys.com/book/)

**Comment by ghost** [comment]
Thanks a bunch! Totally golden! :)

**Comment by fukamachi** [comment]
It's BETA since https://github.com/fukamachi/rove/commit/63af2bc32b25fd17ee28ec26ff961527902e1a23.
Feel free to open another issue when you get some problems.

**Comment by ghost** [comment]
Awesome! Thank you for your work! :)
