### ISSUE TITLE
defhook does not replace hooks

### ISSUE THREAD

**Issue by AlbertoEAF** [fukamachi/rove#49]
The API of `(defhook :before/:after *hook-body*)` is not usable for running lisp images / interactive development. Every time the defhook form is met, which happens when reloading the file / test system or running the file again, etc., will result in adding another hook.

Adding a function named `(rove:clean-hooks)` would work:

`(setf (ROVE/CORE/SUITE/PACKAGE::suite-before-hooks (ROVE/CORE/SUITE/PACKAGE:package-suite *package*)) nil)`

but wouldn't be elegant to have to call it explicitly in the file.

The problem is the hook calls will keep adding up. I.e., if my hook is a `(format t "hook!")` every time I run `(asdf:test-system :my-system)` or reload the file I'll have more and more "hook!" messages showing up before each test.

I see no other solution than naming the hook, so that when the defhook form is met it can replace the old definition. E.g.:

```lisp
(defhook my-db-hook :before 
    ...hook-body)
```

**Comment by fukamachi** [comment]
Sounds troublesome.
I prefer your idea, naming hooks. It would have the same issue as #50, though.

**Comment by AlbertoEAF** [comment]
Thanks Eitaro :)
Can you add this to the readme? The new named defhook form. Otherwise users won't guess this.
