### ISSUE TITLE
ng call prints an erronous statement on console

### ISSUE THREAD

**Issue by sushi-buffer** [fukamachi/rove#6]
Hi!
Noticed that when you write comparisons that expect to return NIL, the tests are run and executed properly, but the console gets false expectations printed.

This test passes correctly:
```lisp
(ng (eql "foo" (copy-seq "foo")))
```
But in console it prints:

 `✓ Expect (EQL foo (COPY-SEQ foo)) to be true.`

which it shouldn't be, right?

**Comment by fukamachi** [comment]
Thanks for reporting. It’ll be fixed.
