### ISSUE TITLE
Misleading documentation for run-suite

### ISSUE THREAD

**Issue by justjoheinz** [fukamachi/rove#68]
The README states that in order to run tests immediately one should invoke

```
(run-suite *package*) 
``` 

however `*package*` returns a package object and there is no method defined for the generic method run-suite which accepts a package. 

```
(run-suite (make-symbol (package-name *package*)))
``` 

seems to work. I am not sure if this is the easiest way to get the symbol for a package, hence I will refrain from making a PR. 

## Error

There is no applicable method for the generic function
  #<STANDARD-GENERIC-FUNCTION ROVE/CORE/SUITE/PACKAGE:RUN-SUITE (2)>
when called with arguments
  (#<PACKAGE "EXAMPLE-LAMBDA/TESTS">).
   [Condition of type SB-PCL::NO-APPLICABLE-METHOD-ERROR]

**Comment by fukamachi** [comment]
Thank you for reporting. It seems because of a lack of a method definition of `run-suite` for package objects.
