### ISSUE TITLE
More questions about reporting

### ISSUE THREAD

**Issue by sushi-buffer** [fukamachi/rove#8]
Hi!

Noticed another thing while doing tests.
When I test for types with '(typep)` I found the output somewhat confusing.
These are not huge problems for me, but if you want I can keep reporting these findings in the future 😄 

So what happens is that when testing:
```
(ok (typep (vector 1 2 3) 'sequence))
```
It prints:
```
✓ Expect (VECTOR 1 2 3) to be an instance of 2.
```

**Comment by fukamachi** [comment]
Thanks for reporting.
