### ISSUE TITLE
A question about signaling errors

### ISSUE THREAD

**Issue by sushi-buffer** [fukamachi/rove#9]
In Rove, how can one test that a correct language level signal is invoked? For example in this case:

``` 
;; NOTE: vec-seq is a plain unadjustable vector created with (vector 1 2 3).
(ok (signals (elt vec-seq 3) 'TYPE-ERROR)
	      "Index too large error"))
```

Resulting in the output of:

```
× 1 of 1 tests failed

0) master-class/test/basics/types/sequence-types
     › cl-sequence-types
       › Generic functions for SEQUENCE subtypes:
         › An 'elt' -function
in the form of: (λ [Vector Integer] Any)
           › Signals error if out of bounds:
   Index too large error
     (SIGNALS (ELT MASTER-CLASS/TEST/BASICS/TYPES/SEQUENCE-TYPES::VEC-SEQ 3)
              'TYPE-ERROR)
```

I've also tried another error types, but the result is always the same.

**Comment by ghost** [comment]
Anything about this? How can I test for out of bound errors? :)

**Comment by fukamachi** [comment]
This is the out-of-scope of Rove, to handle all Common Lisp errors and rethrow as something new.
Consider another approach, handling `ERROR`, checking with `vectorp` beforehand, or handling and checking the error type by yourself.

**Comment by ghost** [comment]
Sorry for taking your time! I wasn't requesting a fix but merely asking a question about expected behavior. Which you've given an answer to :) Seems I need to educate myself a lot more about CLisp error handling and types!
